apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-es-data-efk-cluster-default-0
  namespace: logging
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/es-master-volume/

